apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: event-management # ✅ ADD THIS LINE
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: amnanoor124/my-node-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://i221529:2253149$@cluster0.pkql63w.mongodb.net/?retryWrites=true&w=majority"
