apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: event-management # ✅ ADD THIS LINE
spec:
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
