name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker to use Minikube's Docker daemon (PowerShell compatible)
        shell: powershell
        run: |
          Write-Host "Setting Docker to use Minikube's Docker daemon..."
          Invoke-Expression (& minikube -p minikube docker-env --shell powershell).ToString()

      - name: Build Docker image inside Minikube Docker
        run: docker build -t amnanoor124/my-node-app:latest .

      - name: Deploy to Minikube
        run: |
          cd app
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
